_target_: src.datamodules.SHREC13_shapes.SHREC13_Shapes_Module
data_dir: ${paths.data_dir}
batch_size: 96
num_workers: 0
pin_memory: False
data_mean: [0.9799, 0.9799, 0.9799]
data_std: [0.1075, 0.1075, 0.1075]
nb_points: 2048
dset_norm: 2
